main: me.jedimastersoda.aperture.Aperture
name: ${project.name}
version: ${project.version}
author: JediMasterSoda
description: "A plugin utilizing an exploit in Minecraft 1.8 to check for illegal Minecraft versions."
depend: PacketListenerApi